/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package prog1.game;

public class Game {
    public static void main(String[] args) {
        GameFrame frame = new GameFrame();
    }
}
